### ISSUE TITLE
support for multiple leagues

### ISSUE THREAD

**Issue by barrytam20** [KipFeher85/Fantasy-Baseball#1]
hey there! looks like right now if you have a multiple leagues in yahoo, the `League` class [initializes to your first one](https://github.com/KipFeher85/Fantasy-Baseball/blob/530666d96528dd293c88863753b2fccb3a6f1e51/yahoo_fantasy_baseball_stat_analysis/main.py#L21)

It would be nice if `League.starter()` took in `leagueID` as an optional argument so you could specify which league you wish to run stats on. I would be happy to dust off my python and take a stab at a PR if you like :) 

PS - thanks for your work on this!

**Comment by KipFeher85** [comment]
Barry,

Thanks for using the package. If you want to update to 6.0.1 it will give you the option to pass in a league_id variable. If one is not specified it will display a list of available league ids and will default to the first one

**Comment by KipFeher85** [comment]
Closed with the release of 6.0.2
